/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Code Execution API
 * API for executing code snippets in various programming languages.
 * OpenAPI spec version: 0.1.0
 */
export type RunPythonBody = {
  /**
   * The code snippet to be executed
   * @minLength 1
   */
  code: string;
};

export type RunPython200Output = {
  text?: string;
  html?: string;
  png?: string;
  jpeg?: string;
  svg?: string;
  latex?: string;
  markdown?: string;
  json?: unknown;
  chart?: unknown;
  data?: unknown;
};

export type RunPython200Error = string | null;

export type RunPython200 = {
  success: boolean;
  output?: RunPython200Output;
  error?: RunPython200Error;
};

export type RunPython400 = {
  success: boolean;
  error: string;
};

export type RunJavascriptBody = {
  /**
   * The code snippet to be executed
   * @minLength 1
   */
  code: string;
};

export type RunJavascript200Output = {
  text?: string;
  html?: string;
  png?: string;
  jpeg?: string;
  svg?: string;
  latex?: string;
  markdown?: string;
  json?: unknown;
  chart?: unknown;
  data?: unknown;
};

export type RunJavascript200Error = string | null;

export type RunJavascript200 = {
  success: boolean;
  output?: RunJavascript200Output;
  error?: RunJavascript200Error;
};

export type RunJavascript400 = {
  success: boolean;
  error: string;
};

export type RunTypescriptBody = {
  /**
   * The code snippet to be executed
   * @minLength 1
   */
  code: string;
};

export type RunTypescript200Output = {
  text?: string;
  html?: string;
  png?: string;
  jpeg?: string;
  svg?: string;
  latex?: string;
  markdown?: string;
  json?: unknown;
  chart?: unknown;
  data?: unknown;
};

export type RunTypescript200Error = string | null;

export type RunTypescript200 = {
  success: boolean;
  output?: RunTypescript200Output;
  error?: RunTypescript200Error;
};

export type RunTypescript400 = {
  success: boolean;
  error: string;
};

/**
 * Run Python code
 */
export type runPythonResponse200 = {
  data: RunPython200;
  status: 200;
};

export type runPythonResponse400 = {
  data: RunPython400;
  status: 400;
};

export type runPythonResponseSuccess = runPythonResponse200 & {
  headers: Headers;
};
export type runPythonResponseError = runPythonResponse400 & {
  headers: Headers;
};

export type runPythonResponse =
  | runPythonResponseSuccess
  | runPythonResponseError;

export const getRunPythonUrl = () => {
  return `https://api.uprizing.me/api/v1/run/python`;
};

export const runPython = async (
  runPythonBody: RunPythonBody,
  options?: RequestInit,
): Promise<runPythonResponse> => {
  const res = await fetch(getRunPythonUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(runPythonBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: runPythonResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as runPythonResponse;
};

/**
 * Run Javascript code
 */
export type runJavascriptResponse200 = {
  data: RunJavascript200;
  status: 200;
};

export type runJavascriptResponse400 = {
  data: RunJavascript400;
  status: 400;
};

export type runJavascriptResponseSuccess = runJavascriptResponse200 & {
  headers: Headers;
};
export type runJavascriptResponseError = runJavascriptResponse400 & {
  headers: Headers;
};

export type runJavascriptResponse =
  | runJavascriptResponseSuccess
  | runJavascriptResponseError;

export const getRunJavascriptUrl = () => {
  return `https://api.uprizing.me/api/v1/run/javascript`;
};

export const runJavascript = async (
  runJavascriptBody: RunJavascriptBody,
  options?: RequestInit,
): Promise<runJavascriptResponse> => {
  const res = await fetch(getRunJavascriptUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(runJavascriptBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: runJavascriptResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as runJavascriptResponse;
};

/**
 * Run Typescript code
 */
export type runTypescriptResponse200 = {
  data: RunTypescript200;
  status: 200;
};

export type runTypescriptResponse400 = {
  data: RunTypescript400;
  status: 400;
};

export type runTypescriptResponseSuccess = runTypescriptResponse200 & {
  headers: Headers;
};
export type runTypescriptResponseError = runTypescriptResponse400 & {
  headers: Headers;
};

export type runTypescriptResponse =
  | runTypescriptResponseSuccess
  | runTypescriptResponseError;

export const getRunTypescriptUrl = () => {
  return `https://api.uprizing.me/api/v1/run/typescript`;
};

export const runTypescript = async (
  runTypescriptBody: RunTypescriptBody,
  options?: RequestInit,
): Promise<runTypescriptResponse> => {
  const res = await fetch(getRunTypescriptUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(runTypescriptBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: runTypescriptResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as runTypescriptResponse;
};
