import { defineConfig } from "orval";

export default defineConfig({
  api: {
    input: "http://localhost:8787/v1/openapi.json",
    output: {
      target: "./packages/exec0-node/src/autogenerated/index.ts",
      client: "fetch",
      biome: true,
      clean: true,
      baseUrl: "https://api.uprizing.me",
      docs: true,
    },
  },
});
