import {
  runJavascript,
  type runJavascriptResponse,
  runPython,
  type runPythonResponse,
  runTypescript,
  type runTypescriptResponse,
} from "./autogenerated/index";

export const run = {
  python: (code: string, options?: RequestInit): Promise<runPythonResponse> =>
    runPython({ code }, options),

  javascript: (
    code: string,
    options?: RequestInit,
  ): Promise<runJavascriptResponse> => runJavascript({ code }, options),

  typescript: (
    code: string,
    options?: RequestInit,
  ): Promise<runTypescriptResponse> => runTypescript({ code }, options),
};
