import {
  type RunJavascript200,
  type RunJavascript400,
  type RunPython200,
  type RunPython400,
  type RunTypescript200,
  type RunTypescript400,
  runJavascript,
  runPython,
  runTypescript,
} from "./autogenerated/index";

type NormalizedResponse<T extends { success: boolean }> = {
  data: T & { output: any; error: any };
  status: number;
};

const ensureOutput = (data: any) => data.output || {};
const ensureError = (data: any) => data.error || null;

export const run = {
  python: async (
    code: string,
    options?: RequestInit,
  ): Promise<NormalizedResponse<RunPython200 | RunPython400>> => {
    const response = await runPython({ code }, options);
    return {
      data: {
        ...response.data,
        output: ensureOutput(response.data),
        error: ensureError(response.data),
      },
      status: response.status,
    } as NormalizedResponse<RunPython200 | RunPython400>;
  },

  javascript: async (
    code: string,
    options?: RequestInit,
  ): Promise<NormalizedResponse<RunJavascript200 | RunJavascript400>> => {
    const response = await runJavascript({ code }, options);
    return {
      data: {
        ...response.data,
        output: ensureOutput(response.data),
        error: ensureError(response.data),
      },
      status: response.status,
    } as NormalizedResponse<RunJavascript200 | RunJavascript400>;
  },

  typescript: async (
    code: string,
    options?: RequestInit,
  ): Promise<NormalizedResponse<RunTypescript200 | RunTypescript400>> => {
    const response = await runTypescript({ code }, options);
    return {
      data: {
        ...response.data,
        output: ensureOutput(response.data),
        error: ensureError(response.data),
      },
      status: response.status,
    } as NormalizedResponse<RunTypescript200 | RunTypescript400>;
  },
};
