/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Code Execution API
 * API for executing code snippets in various programming languages.
 * OpenAPI spec version: 0.1.0
 */
export type PostApiV1ExecutePythonBody = {
  /** @minLength 1 */
  code: string;
  /**
   * @maximum 9007199254740991
   */
  timeout?: number;
};

export type PostApiV1ExecutePython200 = {
  output: string;
  error?: string;
  executionTime: number;
};

export type PostApiV1ExecuteJavascriptBody = {
  /** @minLength 1 */
  code: string;
  /**
   * @maximum 9007199254740991
   */
  timeout?: number;
};

export type PostApiV1ExecuteJavascript200 = {
  output: string;
  error?: string;
  executionTime: number;
};

export type PostApiV1ExecuteTypescriptBody = {
  /** @minLength 1 */
  code: string;
  /**
   * @maximum 9007199254740991
   */
  timeout?: number;
};

export type PostApiV1ExecuteTypescript200 = {
  output: string;
  error?: string;
  executionTime: number;
};

/**
 * Execute Python code
 */
export type postApiV1ExecutePythonResponse200 = {
  data: PostApiV1ExecutePython200;
  status: 200;
};

export type postApiV1ExecutePythonResponseSuccess =
  postApiV1ExecutePythonResponse200 & {
    headers: Headers;
  };

export type postApiV1ExecutePythonResponse =
  postApiV1ExecutePythonResponseSuccess;

export const getPostApiV1ExecutePythonUrl = () => {
  return `/api/v1/execute/python`;
};

export const postApiV1ExecutePython = async (
  postApiV1ExecutePythonBody: PostApiV1ExecutePythonBody,
  options?: RequestInit,
): Promise<postApiV1ExecutePythonResponse> => {
  const res = await fetch(getPostApiV1ExecutePythonUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiV1ExecutePythonBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1ExecutePythonResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiV1ExecutePythonResponse;
};

/**
 * Execute JavaScript code
 */
export type postApiV1ExecuteJavascriptResponse200 = {
  data: PostApiV1ExecuteJavascript200;
  status: 200;
};

export type postApiV1ExecuteJavascriptResponseSuccess =
  postApiV1ExecuteJavascriptResponse200 & {
    headers: Headers;
  };

export type postApiV1ExecuteJavascriptResponse =
  postApiV1ExecuteJavascriptResponseSuccess;

export const getPostApiV1ExecuteJavascriptUrl = () => {
  return `/api/v1/execute/javascript`;
};

export const postApiV1ExecuteJavascript = async (
  postApiV1ExecuteJavascriptBody: PostApiV1ExecuteJavascriptBody,
  options?: RequestInit,
): Promise<postApiV1ExecuteJavascriptResponse> => {
  const res = await fetch(getPostApiV1ExecuteJavascriptUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiV1ExecuteJavascriptBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1ExecuteJavascriptResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiV1ExecuteJavascriptResponse;
};

/**
 * Execute TypeScript code
 */
export type postApiV1ExecuteTypescriptResponse200 = {
  data: PostApiV1ExecuteTypescript200;
  status: 200;
};

export type postApiV1ExecuteTypescriptResponseSuccess =
  postApiV1ExecuteTypescriptResponse200 & {
    headers: Headers;
  };

export type postApiV1ExecuteTypescriptResponse =
  postApiV1ExecuteTypescriptResponseSuccess;

export const getPostApiV1ExecuteTypescriptUrl = () => {
  return `/api/v1/execute/typescript`;
};

export const postApiV1ExecuteTypescript = async (
  postApiV1ExecuteTypescriptBody: PostApiV1ExecuteTypescriptBody,
  options?: RequestInit,
): Promise<postApiV1ExecuteTypescriptResponse> => {
  const res = await fetch(getPostApiV1ExecuteTypescriptUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiV1ExecuteTypescriptBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1ExecuteTypescriptResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiV1ExecuteTypescriptResponse;
};
